export const BEFORE = {
  tables: {
    doc_file_paths: {
      name: 'doc_file_paths',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        path: {
          name: 'path',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        is_review_enabled: {
          name: 'is_review_enabled',
          type: 'bool',
          default: true,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        project_id: {
          name: 'project_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        doc_file_path_path_project_id_key: {
          name: 'doc_file_path_path_project_id_key',
          unique: true,
          columns: ['path', 'project_id'],
          type: 'btree',
        },
      },
      constraints: {
        doc_file_paths_organization_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'doc_file_paths_organization_id_fkey',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
        github_doc_file_path_project_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'github_doc_file_path_project_id_fkey',
          columnName: 'project_id',
          targetTableName: 'projects',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
      },
    },
    github_pull_request_comments: {
      name: 'github_pull_request_comments',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        github_pull_request_id: {
          name: 'github_pull_request_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        github_comment_identifier: {
          name: 'github_comment_identifier',
          type: 'int8',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {},
      constraints: {},
    },
    github_pull_requests: {
      name: 'github_pull_requests',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        pull_number: {
          name: 'pull_number',
          type: 'int8',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        repository_id: {
          name: 'repository_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        github_pull_request_repository_id_pull_number_key: {
          name: 'github_pull_request_repository_id_pull_number_key',
          unique: true,
          columns: ['repository_id', 'pull_number'],
          type: 'btree',
        },
      },
      constraints: {
        github_pull_request_repository_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'github_pull_request_repository_id_fkey',
          columnName: 'repository_id',
          targetTableName: 'github_repositories',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
        github_pull_requests_organization_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'github_pull_requests_organization_id_fkey',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
      },
    },
    github_repositories: {
      name: 'github_repositories',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        name: {
          name: 'name',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        owner: {
          name: 'owner',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        github_installation_identifier: {
          name: 'github_installation_identifier',
          type: 'int4',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        github_repository_identifier: {
          name: 'github_repository_identifier',
          type: 'int4',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        github_repository_owner_name_key: {
          name: 'github_repository_owner_name_key',
          unique: true,
          columns: ['owner', 'name'],
          type: 'btree',
        },
      },
      constraints: {
        github_repositories_organization_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'github_repositories_organization_id_fkey',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
      },
    },
    invitations: {
      name: 'invitations',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        email: {
          name: 'email',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        invite_by_user_id: {
          name: 'invite_by_user_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        invited_at: {
          name: 'invited_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        token: {
          name: 'token',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        expired_at: {
          name: 'expired_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        invitations_email_idx: {
          name: 'invitations_email_idx',
          unique: false,
          columns: ['email'],
          type: 'btree',
        },
        invitations_organization_id_idx: {
          name: 'invitations_organization_id_idx',
          unique: false,
          columns: ['organization_id'],
          type: 'btree',
        },
      },
      constraints: {
        invitations_invite_by_user_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'invitations_invite_by_user_id_fkey',
          columnName: 'invite_by_user_id',
          targetTableName: 'users',
          targetColumnName: 'id',
          updateConstraint: 'NO_ACTION',
          deleteConstraint: 'CASCADE',
        },
        invitations_organization_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'invitations_organization_id_fkey',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'NO_ACTION',
          deleteConstraint: 'CASCADE',
        },
      },
    },
    knowledge_suggestion_doc_mappings: {
      name: 'knowledge_suggestion_doc_mappings',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        knowledge_suggestion_id: {
          name: 'knowledge_suggestion_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        doc_file_path_id: {
          name: 'doc_file_path_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        knowledge_suggestion_doc_mapping_unique_mapping: {
          name: 'knowledge_suggestion_doc_mapping_unique_mapping',
          unique: true,
          columns: ['knowledge_suggestion_id', 'doc_file_path_id'],
          type: 'btree',
        },
      },
      constraints: {
        knowledge_suggestion_doc_mapping_doc_file_path_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'knowledge_suggestion_doc_mapping_doc_file_path_id_fkey',
          columnName: 'doc_file_path_id',
          targetTableName: 'doc_file_paths',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'CASCADE',
        },
        knowledge_suggestion_doc_mapping_knowledge_suggestion_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'knowledge_suggestion_doc_mapping_knowledge_suggestion_id_fkey',
          columnName: 'knowledge_suggestion_id',
          targetTableName: 'knowledge_suggestions',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'CASCADE',
        },
        knowledge_suggestion_doc_mappings_organization_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'knowledge_suggestion_doc_mappings_organization_id_fkey',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
      },
    },
    knowledge_suggestions: {
      name: 'knowledge_suggestions',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        type: {
          name: 'type',
          type: 'publicknowledge_type',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        title: {
          name: 'title',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        path: {
          name: 'path',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        content: {
          name: 'content',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        file_sha: {
          name: 'file_sha',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        project_id: {
          name: 'project_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        approved_at: {
          name: 'approved_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        branch_name: {
          name: 'branch_name',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        trace_id: {
          name: 'trace_id',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        reasoning: {
          name: 'reasoning',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {},
      constraints: {},
    },
    migration_pull_request_mappings: {
      name: 'migration_pull_request_mappings',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        migration_id: {
          name: 'migration_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        pull_request_id: {
          name: 'pull_request_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {},
      constraints: {},
    },
    migrations: {
      name: 'migrations',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        title: {
          name: 'title',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        project_id: {
          name: 'project_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {},
      constraints: {},
    },
    organization_members: {
      name: 'organization_members',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        user_id: {
          name: 'user_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        joined_at: {
          name: 'joined_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        organization_member_organization_id_idx: {
          name: 'organization_member_organization_id_idx',
          unique: false,
          columns: ['organization_id'],
          type: 'btree',
        },
        organization_member_user_id_idx: {
          name: 'organization_member_user_id_idx',
          unique: false,
          columns: ['user_id'],
          type: 'btree',
        },
      },
      constraints: {
        organization_member_organization_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'organization_member_organization_id_fkey',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'NO_ACTION',
          deleteConstraint: 'CASCADE',
        },
        organization_member_user_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'organization_member_user_id_fkey',
          columnName: 'user_id',
          targetTableName: 'users',
          targetColumnName: 'id',
          updateConstraint: 'NO_ACTION',
          deleteConstraint: 'CASCADE',
        },
      },
    },
    organizations: {
      name: 'organizations',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        name: {
          name: 'name',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {},
      constraints: {},
    },
    overall_review_knowledge_suggestion_mappings: {
      name: 'overall_review_knowledge_suggestion_mappings',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        overall_review_id: {
          name: 'overall_review_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        knowledge_suggestion_id: {
          name: 'knowledge_suggestion_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        overall_review_knowledge_suggestion_mapping_unique_mapping: {
          name: 'overall_review_knowledge_suggestion_mapping_unique_mapping',
          unique: true,
          columns: ['overall_review_id', 'knowledge_suggestion_id'],
          type: 'btree',
        },
      },
      constraints: {
        overall_review_knowledge_suggestion_mapping_knowledge_suggestio: {
          type: 'FOREIGN KEY',
          name: 'overall_review_knowledge_suggestion_mapping_knowledge_suggestio',
          columnName: 'knowledge_suggestion_id',
          targetTableName: 'knowledge_suggestions',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'CASCADE',
        },
        overall_review_knowledge_suggestion_mapping_overall_review_id_f: {
          type: 'FOREIGN KEY',
          name: 'overall_review_knowledge_suggestion_mapping_overall_review_id_f',
          columnName: 'overall_review_id',
          targetTableName: 'overall_reviews',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'CASCADE',
        },
        overall_review_knowledge_suggestion_mappings_organization_id_fk: {
          type: 'FOREIGN KEY',
          name: 'overall_review_knowledge_suggestion_mappings_organization_id_fk',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
      },
    },
    overall_reviews: {
      name: 'overall_reviews',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        review_comment: {
          name: 'review_comment',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        reviewed_at: {
          name: 'reviewed_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        branch_name: {
          name: 'branch_name',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        trace_id: {
          name: 'trace_id',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        migration_id: {
          name: 'migration_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {},
      constraints: {},
    },
    project_repository_mappings: {
      name: 'project_repository_mappings',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        project_id: {
          name: 'project_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        repository_id: {
          name: 'repository_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        project_repository_mapping_project_id_repository_id_key: {
          name: 'project_repository_mapping_project_id_repository_id_key',
          unique: true,
          columns: ['project_id', 'repository_id'],
          type: 'btree',
        },
      },
      constraints: {
        project_repository_mapping_project_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'project_repository_mapping_project_id_fkey',
          columnName: 'project_id',
          targetTableName: 'projects',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
        project_repository_mapping_repository_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'project_repository_mapping_repository_id_fkey',
          columnName: 'repository_id',
          targetTableName: 'github_repositories',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
        project_repository_mappings_organization_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'project_repository_mappings_organization_id_fkey',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
      },
    },
    projects: {
      name: 'projects',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        name: {
          name: 'name',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        idx_project_organization_id: {
          name: 'idx_project_organization_id',
          unique: false,
          columns: ['organization_id'],
          type: 'btree',
        },
      },
      constraints: {
        project_organization_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'project_organization_id_fkey',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'CASCADE',
        },
      },
    },
    review_feedback_comments: {
      name: 'review_feedback_comments',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        review_feedback_id: {
          name: 'review_feedback_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        user_id: {
          name: 'user_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        content: {
          name: 'content',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        idx_review_feedback_comment_review_feedback_id: {
          name: 'idx_review_feedback_comment_review_feedback_id',
          unique: false,
          columns: ['review_feedback_id'],
          type: 'btree',
        },
      },
      constraints: {
        review_feedback_comment_review_feedback_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'review_feedback_comment_review_feedback_id_fkey',
          columnName: 'review_feedback_id',
          targetTableName: 'review_feedbacks',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'CASCADE',
        },
        review_feedback_comment_user_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'review_feedback_comment_user_id_fkey',
          columnName: 'user_id',
          targetTableName: 'users',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'CASCADE',
        },
        review_feedback_comments_organization_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'review_feedback_comments_organization_id_fkey',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
      },
    },
    review_feedback_knowledge_suggestion_mappings: {
      name: 'review_feedback_knowledge_suggestion_mappings',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        review_feedback_id: {
          name: 'review_feedback_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        knowledge_suggestion_id: {
          name: 'knowledge_suggestion_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {},
      constraints: {},
    },
    review_feedbacks: {
      name: 'review_feedbacks',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        overall_review_id: {
          name: 'overall_review_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        category: {
          name: 'category',
          type: 'publiccategory_enum',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        severity: {
          name: 'severity',
          type: 'publicseverity_enum',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        description: {
          name: 'description',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        suggestion: {
          name: 'suggestion',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        resolved_at: {
          name: 'resolved_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        resolution_comment: {
          name: 'resolution_comment',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: false,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {},
      constraints: {},
    },
    review_suggestion_snippets: {
      name: 'review_suggestion_snippets',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        review_feedback_id: {
          name: 'review_feedback_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        filename: {
          name: 'filename',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        snippet: {
          name: 'snippet',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {},
      constraints: {},
    },
    schema_file_paths: {
      name: 'schema_file_paths',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        path: {
          name: 'path',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        project_id: {
          name: 'project_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        created_at: {
          name: 'created_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        updated_at: {
          name: 'updated_at',
          type: 'timestamptz',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        format: {
          name: 'format',
          type: 'publicschema_format_enum',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        organization_id: {
          name: 'organization_id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {
        schema_file_path_path_project_id_key: {
          name: 'schema_file_path_path_project_id_key',
          unique: true,
          columns: ['path', 'project_id'],
          type: 'btree',
        },
        schema_file_path_project_id_key: {
          name: 'schema_file_path_project_id_key',
          unique: true,
          columns: ['project_id'],
          type: 'btree',
        },
      },
      constraints: {
        schema_file_path_project_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'schema_file_path_project_id_fkey',
          columnName: 'project_id',
          targetTableName: 'projects',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
        schema_file_paths_organization_id_fkey: {
          type: 'FOREIGN KEY',
          name: 'schema_file_paths_organization_id_fkey',
          columnName: 'organization_id',
          targetTableName: 'organizations',
          targetColumnName: 'id',
          updateConstraint: 'CASCADE',
          deleteConstraint: 'RESTRICT',
        },
      },
    },
    users: {
      name: 'users',
      columns: {
        id: {
          name: 'id',
          type: 'uuid',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        name: {
          name: 'name',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
        email: {
          name: 'email',
          type: 'text',
          default: null,
          check: null,
          primary: false,
          unique: false,
          notNull: true,
          comment: null,
        },
      },
      comment: null,
      indexes: {},
      constraints: {},
    },
  },
  relationships: {
    doc_file_paths_organization_id_fkey: {
      name: 'doc_file_paths_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'doc_file_paths',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    github_doc_file_path_project_id_fkey: {
      name: 'github_doc_file_path_project_id_fkey',
      primaryTableName: 'projects',
      primaryColumnName: 'id',
      foreignTableName: 'doc_file_paths',
      foreignColumnName: 'project_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    github_pull_request_comments_github_pull_request_id_fkey: {
      name: 'github_pull_request_comments_github_pull_request_id_fkey',
      primaryTableName: 'github_pull_requests',
      primaryColumnName: 'id',
      foreignTableName: 'github_pull_request_comments',
      foreignColumnName: 'github_pull_request_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    github_pull_request_comments_organization_id_fkey: {
      name: 'github_pull_request_comments_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'github_pull_request_comments',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    github_pull_request_repository_id_fkey: {
      name: 'github_pull_request_repository_id_fkey',
      primaryTableName: 'github_repositories',
      primaryColumnName: 'id',
      foreignTableName: 'github_pull_requests',
      foreignColumnName: 'repository_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    github_pull_requests_organization_id_fkey: {
      name: 'github_pull_requests_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'github_pull_requests',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    github_repositories_organization_id_fkey: {
      name: 'github_repositories_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'github_repositories',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    invitations_invite_by_user_id_fkey: {
      name: 'invitations_invite_by_user_id_fkey',
      primaryTableName: 'users',
      primaryColumnName: 'id',
      foreignTableName: 'invitations',
      foreignColumnName: 'invite_by_user_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'NO_ACTION',
      deleteConstraint: 'CASCADE',
    },
    invitations_organization_id_fkey: {
      name: 'invitations_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'invitations',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'NO_ACTION',
      deleteConstraint: 'CASCADE',
    },
    knowledge_suggestion_doc_mapping_doc_file_path_id_fkey: {
      name: 'knowledge_suggestion_doc_mapping_doc_file_path_id_fkey',
      primaryTableName: 'doc_file_paths',
      primaryColumnName: 'id',
      foreignTableName: 'knowledge_suggestion_doc_mappings',
      foreignColumnName: 'doc_file_path_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    knowledge_suggestion_doc_mapping_knowledge_suggestion_id_fkey: {
      name: 'knowledge_suggestion_doc_mapping_knowledge_suggestion_id_fkey',
      primaryTableName: 'knowledge_suggestions',
      primaryColumnName: 'id',
      foreignTableName: 'knowledge_suggestion_doc_mappings',
      foreignColumnName: 'knowledge_suggestion_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    knowledge_suggestion_doc_mappings_organization_id_fkey: {
      name: 'knowledge_suggestion_doc_mappings_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'knowledge_suggestion_doc_mappings',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    knowledge_suggestion_project_id_fkey: {
      name: 'knowledge_suggestion_project_id_fkey',
      primaryTableName: 'projects',
      primaryColumnName: 'id',
      foreignTableName: 'knowledge_suggestions',
      foreignColumnName: 'project_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    knowledge_suggestions_organization_id_fkey: {
      name: 'knowledge_suggestions_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'knowledge_suggestions',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    migration_project_id_fkey: {
      name: 'migration_project_id_fkey',
      primaryTableName: 'projects',
      primaryColumnName: 'id',
      foreignTableName: 'migrations',
      foreignColumnName: 'project_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    migration_pull_request_mapping_migration_id_fkey: {
      name: 'migration_pull_request_mapping_migration_id_fkey',
      primaryTableName: 'migrations',
      primaryColumnName: 'id',
      foreignTableName: 'migration_pull_request_mappings',
      foreignColumnName: 'migration_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    migration_pull_request_mapping_pull_request_id_fkey: {
      name: 'migration_pull_request_mapping_pull_request_id_fkey',
      primaryTableName: 'github_pull_requests',
      primaryColumnName: 'id',
      foreignTableName: 'migration_pull_request_mappings',
      foreignColumnName: 'pull_request_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    migration_pull_request_mappings_organization_id_fkey: {
      name: 'migration_pull_request_mappings_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'migration_pull_request_mappings',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    migrations_organization_id_fkey: {
      name: 'migrations_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'migrations',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    organization_member_organization_id_fkey: {
      name: 'organization_member_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'organization_members',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'NO_ACTION',
      deleteConstraint: 'CASCADE',
    },
    organization_member_user_id_fkey: {
      name: 'organization_member_user_id_fkey',
      primaryTableName: 'users',
      primaryColumnName: 'id',
      foreignTableName: 'organization_members',
      foreignColumnName: 'user_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'NO_ACTION',
      deleteConstraint: 'CASCADE',
    },
    overall_review_knowledge_suggestion_mapping_knowledge_suggestio: {
      name: 'overall_review_knowledge_suggestion_mapping_knowledge_suggestio',
      primaryTableName: 'knowledge_suggestions',
      primaryColumnName: 'id',
      foreignTableName: 'overall_review_knowledge_suggestion_mappings',
      foreignColumnName: 'knowledge_suggestion_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    overall_review_knowledge_suggestion_mapping_overall_review_id_f: {
      name: 'overall_review_knowledge_suggestion_mapping_overall_review_id_f',
      primaryTableName: 'overall_reviews',
      primaryColumnName: 'id',
      foreignTableName: 'overall_review_knowledge_suggestion_mappings',
      foreignColumnName: 'overall_review_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    overall_review_knowledge_suggestion_mappings_organization_id_fk: {
      name: 'overall_review_knowledge_suggestion_mappings_organization_id_fk',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'overall_review_knowledge_suggestion_mappings',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    overall_review_migration_id_fkey: {
      name: 'overall_review_migration_id_fkey',
      primaryTableName: 'migrations',
      primaryColumnName: 'id',
      foreignTableName: 'overall_reviews',
      foreignColumnName: 'migration_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    overall_reviews_organization_id_fkey: {
      name: 'overall_reviews_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'overall_reviews',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    project_organization_id_fkey: {
      name: 'project_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'projects',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    project_repository_mapping_project_id_fkey: {
      name: 'project_repository_mapping_project_id_fkey',
      primaryTableName: 'projects',
      primaryColumnName: 'id',
      foreignTableName: 'project_repository_mappings',
      foreignColumnName: 'project_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    project_repository_mapping_repository_id_fkey: {
      name: 'project_repository_mapping_repository_id_fkey',
      primaryTableName: 'github_repositories',
      primaryColumnName: 'id',
      foreignTableName: 'project_repository_mappings',
      foreignColumnName: 'repository_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    project_repository_mappings_organization_id_fkey: {
      name: 'project_repository_mappings_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'project_repository_mappings',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    review_feedback_comment_review_feedback_id_fkey: {
      name: 'review_feedback_comment_review_feedback_id_fkey',
      primaryTableName: 'review_feedbacks',
      primaryColumnName: 'id',
      foreignTableName: 'review_feedback_comments',
      foreignColumnName: 'review_feedback_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    review_feedback_comment_user_id_fkey: {
      name: 'review_feedback_comment_user_id_fkey',
      primaryTableName: 'users',
      primaryColumnName: 'id',
      foreignTableName: 'review_feedback_comments',
      foreignColumnName: 'user_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    review_feedback_comments_organization_id_fkey: {
      name: 'review_feedback_comments_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'review_feedback_comments',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    review_feedback_knowledge_suggesti_knowledge_suggestion_id_fkey: {
      name: 'review_feedback_knowledge_suggesti_knowledge_suggestion_id_fkey',
      primaryTableName: 'knowledge_suggestions',
      primaryColumnName: 'id',
      foreignTableName: 'review_feedback_knowledge_suggestion_mappings',
      foreignColumnName: 'knowledge_suggestion_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'NO_ACTION',
      deleteConstraint: 'NO_ACTION',
    },
    review_feedback_knowledge_suggestion_ma_review_feedback_id_fkey: {
      name: 'review_feedback_knowledge_suggestion_ma_review_feedback_id_fkey',
      primaryTableName: 'review_feedbacks',
      primaryColumnName: 'id',
      foreignTableName: 'review_feedback_knowledge_suggestion_mappings',
      foreignColumnName: 'review_feedback_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'NO_ACTION',
      deleteConstraint: 'NO_ACTION',
    },
    review_feedback_knowledge_suggestion_mappings_organization_id_f: {
      name: 'review_feedback_knowledge_suggestion_mappings_organization_id_f',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'review_feedback_knowledge_suggestion_mappings',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    review_feedback_overall_review_id_fkey: {
      name: 'review_feedback_overall_review_id_fkey',
      primaryTableName: 'overall_reviews',
      primaryColumnName: 'id',
      foreignTableName: 'review_feedbacks',
      foreignColumnName: 'overall_review_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    review_feedbacks_organization_id_fkey: {
      name: 'review_feedbacks_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'review_feedbacks',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    review_suggestion_snippet_review_feedback_id_fkey: {
      name: 'review_suggestion_snippet_review_feedback_id_fkey',
      primaryTableName: 'review_feedbacks',
      primaryColumnName: 'id',
      foreignTableName: 'review_suggestion_snippets',
      foreignColumnName: 'review_feedback_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'CASCADE',
    },
    review_suggestion_snippets_organization_id_fkey: {
      name: 'review_suggestion_snippets_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'review_suggestion_snippets',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    schema_file_path_project_id_fkey: {
      name: 'schema_file_path_project_id_fkey',
      primaryTableName: 'projects',
      primaryColumnName: 'id',
      foreignTableName: 'schema_file_paths',
      foreignColumnName: 'project_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
    schema_file_paths_organization_id_fkey: {
      name: 'schema_file_paths_organization_id_fkey',
      primaryTableName: 'organizations',
      primaryColumnName: 'id',
      foreignTableName: 'schema_file_paths',
      foreignColumnName: 'organization_id',
      cardinality: 'ONE_TO_MANY',
      updateConstraint: 'CASCADE',
      deleteConstraint: 'RESTRICT',
    },
  },
  tableGroups: {},
} as const
