export {
  type DBStructure,
  type Table,
  type Tables,
  type Columns,
  type Column,
  type Index,
  type Indexes,
  type Relationships,
  type Cardinality,
  type TableGroup,
  type DBOverride,
  type Constraints,
  type PrimaryKeyConstraint,
  type ForeignKeyConstraint,
  type UniqueConstraint,
  type CheckConstraint,
  dbStructureSchema,
  aTable,
  aColumn,
  aRelationship,
  applyOverrides,
  dbOverrideSchema,
  tableGroupSchema,
  tableGroupsSchema,
} from './schema/index.js'

export type { ProcessError } from './parser.js'
